# Generated by Django 3.0.6 on 2020-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creater', models.CharField(max_length=50)),
                ('fav', models.IntegerField()),
                ('live', models.BooleanField()),
                ('subscription', models.IntegerField()),
                ('link1', models.TextField()),
                ('link2', models.TextField()),
                ('link3', models.TextField()),
                ('img1', models.TextField()),
                ('img2', models.TextField()),
                ('img3', models.TextField()),
            ],
        ),
    ]
